%YAML:1.0

#common parameters
imu_topic: "/imu/data"
image_topic: "/camera/image_raw"
output_path: "/root"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: -0.128609129935355
   k2: 0.193202233206988
   p1: 0
   p2: 0
projection_parameters:
   fx: 841.54982132
   fy: 843.2498246
   cx: 423.6718105808
   cy: 270.951880042

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0  # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.99985032, -0.00923253, 0.01463228,
          0.01434213, -0.03074719, -0.99942429, 
          0.00967711, 0.99948455,-0.03061017]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.02643998, -0.06031053, 0.04885499]

#feature traker paprameters
max_cnt: 100            # max feature number in feature tracking
min_dist: 20            # min distance between two features 
freq: 0              # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.01          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.005         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0002         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 4.0e-6       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/shaozu/output/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.015334
                   # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ


# Thermal stuff
mini_intensity: 0.0  # the minimal value of current thermal image for JFR_Parkinglot dataset   #21000 for indoor air lab   #19000 for outdoor 
scale_factor: 65535.0    # the scale factor for current thermal image for JFR_Parkinglot dataset      # 0.08 (4000) for indor air lab    # 0.12 for outdoor    
clache_limit: 2.0       # the parmameter for image contrast "CLACHE"
clache_window_size: 16    # the parameter for image contrast "CLACHE"



# 16bit KLT tracking Parameter
paramid_level: 2   #  the number of 16 bit parammid level
max_iter: 5     # The maxium of iteration in KLT feature tracking
flow_back_distance: 0.006 # The maxium distance threshold of flow back. if large than this, remove correspoinding features.
eigen_value_minimum: 1.0e-8 # The Hessian matrix of current feauture should have a large eigen value; small than this value, we ignore.
eigen_value_ratio: 5.0     # The eigen value lama1 and lama 2 should have similar magnitude

#Parameter for thermal point
border: 16    # border value for thermal point selection
NMS_dist_thresh: 4 # NMS value for thermal point selection
detection_thresh: 0.01 # detection threshold for thermal point on hawkins smoke deatset